"""
Seeds the database from the realistic EPC documents already present in
backend/storage/ (generated by sample_data/generate_samples.py), plus
the Primavera schedule and procurement status CSVs.

Previously this only inserted 3 hand-written stub rows from
seed_documents.json, while ~30 real generated PDFs/DOCX/XLSX sat in
backend/storage/ completely unregistered -- invisible to Documents,
Search, Chat, and Compliance. This now does real ingestion: extract
text, chunk it, extract metadata, and insert.
"""
import json
import sqlite3
from pathlib import Path

from backend.services.extraction_service import extract_text
from backend.services.metadata_extractor import extract_metadata

STORAGE_DIR = Path(__file__).resolve().parents[1] / "storage"
SAMPLE_DATA_DIR = Path(__file__).resolve().parents[2] / "sample_data"

# Files in backend/storage that follow the generator's doc_###_Category
# naming convention. Anything else (e.g. an unrelated personal upload)
# is skipped so we don't pollute the EPC document hub.
_DOC_PATTERN = "doc_*"


def seed_sample_documents() -> None:
    """Each source is seeded independently and idempotently, so re-running
    (or upgrading an older DB that only had the 3 legacy stub rows) fills
    in whatever is missing instead of a single all-or-nothing count check."""
    from backend.database.init_db import DB_PATH

    conn = sqlite3.connect(DB_PATH)

    already_has_storage_docs = conn.execute(
        "SELECT COUNT(*) FROM documents WHERE file_name LIKE 'doc\\_%' ESCAPE '\\'"
    ).fetchone()[0] > 0
    if not already_has_storage_docs:
        _seed_storage_documents(conn)

    already_has_stub_docs = conn.execute(
        "SELECT COUNT(*) FROM documents WHERE file_name = 'client-ups-spec.pdf'"
    ).fetchone()[0] > 0
    if not already_has_stub_docs:
        _seed_legacy_json_stub(conn)

    already_has_schedule = conn.execute(
        "SELECT COUNT(*) FROM documents WHERE document_type = 'SCHEDULE'"
    ).fetchone()[0] > 0
    if not already_has_schedule:
        _seed_schedule_csv(conn)

    already_has_procurement = conn.execute(
        "SELECT COUNT(*) FROM documents WHERE file_name = 'procurement.import'"
    ).fetchone()[0] > 0
    if not already_has_procurement:
        _seed_procurement_csv(conn)

    conn.close()


def _seed_storage_documents(conn: sqlite3.Connection) -> None:
    files = sorted(STORAGE_DIR.glob(_DOC_PATTERN))
    for file_path in files:
        try:
            text_body, chunks = extract_text(file_path)
        except Exception as exc:  # corrupted/unreadable file: skip, don't crash startup
            print(f"[seed] failed to parse {file_path.name}: {exc}")
            continue

        meta = extract_metadata(text_body, file_path.name)
        category = meta["document_category"]
        name_part = file_path.stem.split("_", 2)
        doc_number = name_part[1] if len(name_part) == 3 and name_part[1].isdigit() else None

        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO documents (title, file_name, document_type, vendor, project, revision, issue_date, approval_status, equipment_ids, drawing_numbers, spec_references, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'processed')
            """,
            (
                f"{category} #{doc_number}" if doc_number else file_path.stem,
                file_path.name,
                category,
                meta.get("vendor") or "Unspecified",
                "Riyadh Data Centre EPC Program",
                meta.get("revision") or "Unspecified",
                meta.get("issue_date") or "",
                meta.get("approval_status") or "Pending",
                ", ".join(meta.get("equipment_ids") or []),
                ", ".join(meta.get("drawing_numbers") or []),
                ", ".join(meta.get("spec_references") or []),
            ),
        )
        document_id = cursor.lastrowid

        for index, chunk in enumerate(chunks, start=1):
            content = chunk.get("content", "") if isinstance(chunk, dict) else str(chunk)
            section = chunk.get("section", f"Section {index}") if isinstance(chunk, dict) else f"Section {index}"
            page_number = chunk.get("page_number", 1) if isinstance(chunk, dict) else 1
            conn.execute(
                "INSERT INTO chunks (document_id, content, section, page_number, metadata) VALUES (?, ?, ?, ?, ?)",
                (document_id, content, section, page_number, json.dumps({"source": file_path.name})),
            )
        conn.execute(
            "INSERT INTO document_versions (document_id, version) VALUES (?, ?)",
            (document_id, meta.get("revision") or "Unspecified"),
        )
    conn.commit()
    print(f"[seed] ingested {len(files)} documents from backend/storage")


def _seed_legacy_json_stub(conn: sqlite3.Connection) -> None:
    """Keep the original 3 hand-written showcase rows too (nice titles, no file needed)."""
    data_path = SAMPLE_DATA_DIR / "seed_documents.json"
    if not data_path.exists():
        return
    with data_path.open("r", encoding="utf-8") as handle:
        rows = json.load(handle)
    for item in rows:
        conn.execute(
            """
            INSERT INTO documents (title, file_name, document_type, vendor, project, revision, issue_date, approval_status, equipment_ids, drawing_numbers, spec_references, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'processed')
            """,
            (
                item["title"],
                item["file_name"],
                item["document_type"],
                item["vendor"],
                item["project"],
                item["revision"],
                item["issue_date"],
                item["approval_status"],
                item["equipment_ids"],
                item["drawing_numbers"],
                item["spec_references"],
            ),
        )
    conn.commit()


def _seed_schedule_csv(conn: sqlite3.Connection) -> None:
    from backend.services.schedule_service import ScheduleService

    csv_path = SAMPLE_DATA_DIR / "primavera_schedule.csv"
    if not csv_path.exists():
        return
    try:
        ScheduleService().ingest_schedule(str(csv_path))
    except Exception as exc:
        print(f"[seed] failed to ingest Primavera schedule: {exc}")


def _seed_procurement_csv(conn: sqlite3.Connection) -> None:
    from backend.services.connector_service import ConnectorService

    csv_path = SAMPLE_DATA_DIR / "procurement_status.csv"
    if not csv_path.exists():
        return
    try:
        ConnectorService().ingest_csv(str(csv_path), source_type="procurement")
    except Exception as exc:
        print(f"[seed] failed to ingest procurement status: {exc}")
